### ISSUE TITLE
这个颜色

### ISSUE THREAD

**Issue by niyangup** [luckysmg/flutter_swipe_action_cell#10]
![518318DB-53F5-4B81-9A8B-5421E78BE0F8](https://user-images.githubusercontent.com/49631899/99344860-0529d880-28cc-11eb-854a-96397fb6003e.png)
这个颜色能改成上面透明的咩 下面的会给整个item套上一个颜色

**Comment by luckysmg** [comment]
好的，回头我定制一下啊这个参数，这个貌似会影响整个的颜色，今天修复

**Comment by niyangup** [comment]
good good~

**Comment by luckysmg** [comment]
因为我的编辑的按钮实际上是摆在这个cell下面的，所以如果是透明颜色的话就会看见这个编辑按钮，我可以设置一个backgroundColor参数，让你去自定义这个颜色，不定义的话默认值就是这个Theme.of(context)这个值，我觉得这样可能好一些，不然我要控制编辑按钮的显示的话动画效果看起来不是很好

**Comment by niyangup** [comment]
当然可以~

**Comment by luckysmg** [comment]
行，这边马上会推送下一个版本

**Comment by luckysmg** [comment]
目前已经推送了v1.2.3,过一会儿你可以试一下，可以自定义你想要的背景颜色

**Comment by niyangup** [comment]
可以了~

**Comment by luckysmg** [comment]
行，没什么问题我就关闭这个issue了😀
