### ISSUE TITLE
Cannot get size from a render object that has been marked dirty for layout

### ISSUE THREAD

**Issue by TerryLiu** [luckysmg/flutter_swipe_action_cell#12]
**问题描述:**
在列表视图滑动到最后几行时,就会报出如下红字:
"Cannot get size from a render object that has been marked dirty for layout"
已经被该问题困扰了几天.

issue貌似来自:
package:flutter_swipe_action_cell/core/cell.dart:929:50
>   @override
  void didUpdateWidget(_ContentWidget oldWidget) {
    super.didUpdateWidget(oldWidget);
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      if (mounted) widget.onLayoutUpdate(context.size);
    });
  }

**完整的报错信息:**

════════ Exception caught by scheduler library ═══════════════════════════
The following assertion was thrown during a scheduler callback:
Cannot get size from a render object that has been marked dirty for layout.

The size of this render object is ambiguous because this render object has been modified since it was last laid out, which typically means that the size getter was called too early in the pipeline (e.g., during the build phase) before the framework has determined the size and position of the render objects during layout.

The size getter was called for the following element: _ContentWidget
  state: __ContentWidgetState#a7aaf
The render object from which the size was to be obtained was: RenderTransform#45058 NEEDS-LAYOUT NEEDS-PAINT
...  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(0.0<=w<=346.0, 0.0<=h<=Infinity)
...  size: Size(346.0, 72.0)
...  transform matrix: [0] 1.0,0.0,0.0,0.0
[1] 0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...  origin: null
...  alignment: null
...  textDirection: ltr
...  transformHitTests: false

Consider using debugPrintMarkNeedsLayoutStacks to determine why the render object in question is dirty, if you did not expect this.

When the exception was thrown, this was the stack: 
#0      Element.size.<anonymous closure> (package:flutter/src/widgets/framework.dart:3875:9)
#1      Element.size (package:flutter/src/widgets/framework.dart:3893:6)
#2      __ContentWidgetState.didUpdateWidget.<anonymous closure> (package:flutter_swipe_action_cell/core/cell.dart:929:50)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1063:9)
...

**pubspec.yaml使用的版本**
flutter_swipe_action_cell: ^1.2.3 

**我的源码片段**
是在ListView的itemBuilder中使用的:

Widget renderItemType([BuildContext context,List<Funds> list,int idx]){
    return SwipeActionCell(
      key: ObjectKey(list[idx]),
      child: ListItem(key:ValueKey(list[idx].code),leftTime:list[idx].lastTime,bigTitle:list[idx].name,subTitle:list[idx].code),
      trailingActions: <SwipeAction>[
        SwipeAction(
          title: '删除',
          style:TS.textWhite14,
          color: Colors.red,
          icon: Icon(Icons.delete,color: Colors.white,),
          onTap: (CompletionHandler handler) async {
            await handler(true);
            list.removeAt(idx);
            setState(() {});
          },

        ),
      ],
    );
  }

**我的开发环境:**
flutter doctor -v
[√] Flutter (Channel unknown, 1.22.3, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.22.3 at D:\android\flutter
    • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\android\Sdk
    • Java binary at: D:\android\Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\android\Studio
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

**Comment by luckysmg** [comment]
你能否提供一下你的完整的源代码，比如你的ListItem的源代码

**Comment by luckysmg** [comment]
如果你的源代码里面包含你的业务逻辑不好展示的话，你可以写一个小demo，包含最少的内容并且能重现你的问题的一个demo，因为不排除这是你的代码的问题，因为在尝试过程中我这里没有出现问题，谢谢！

**Comment by TerryLiu** [comment]
[demo.zip](https://github.com/luckysmg/flutter_swipe_action_cell/files/5571301/demo.zip)
附件中是list所在的页面代码, 反复上下滑动页面几次, 在滑动到页面底部时就会重现issue.
您试试看

**Comment by luckysmg** [comment]
好的，收到，我会看一下

**Comment by TerryLiu** [comment]
> 好的，收到，我会看一下

我在线,不关页面, demo若有问题,请即时联系

**Comment by luckysmg** [comment]
好的

**Comment by luckysmg** [comment]
我这里试了一下，因为我这里没有你的一些参数，所以我就将一些参数设置成静态了的，代码如下，测试了没有发现问题。
```dart
class HomePage extends StatefulWidget {
  /// {@macro counter_page}
  HomePage({Key key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  // 为列表创建20条数据
  List<int> list = List.generate(20, (index) {
    return index;
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        // backgroundColor: Colors.white,
        appBar: AppBar(
          // brightness: Brightness.light,
          elevation: 0.0,
          //右侧的图标按钮
          actions: [
            Semantics(
              label: "搜索一下",
              child: IconButton(
                  icon: Icon(Icons.search),
                  onPressed: () {
                    //TODO 搜索功能
                    debugPrint('搜索一下');
                  }),
            ),
          ],
        ),
        body: Container(
          //使用带分割线的列表视图
          child: ListView.separated(
            itemCount: list.length,
            //这个分割线的高度必须设置,否则会很出现多余的边距
            separatorBuilder: (BuildContext context, int index) =>
                Divider(height: 0.6),
            itemBuilder: (BuildContext context, int index) {
              // 直接使用list就不会报错
              // return ListItem(key:ValueKey(list[index].code),leftTime:list[index].lastTime,bigTitle:list[index].name,subTitle:list[index].code);
              // 使用侧滑删除组件就会报错
              return renderItemType(context, index);
            },
          ),
        ));
  }

  //单个列表项的抽屉菜单封装
  Widget renderItemType(context, index) {
    //使用第三方的侧滑删除组件
    return SwipeActionCell(
      ///这个key是必要的
      key: ObjectKey(list[index]),
      child: ListItem(
        key: ValueKey(list[index]),
        index: index,
        //左侧按钮列表
        // actions: <Widget>[],
        //右侧按钮列表
      ),
      trailingActions: <SwipeAction>[
        SwipeAction(
          title: '删除',
          color: Colors.red,
          icon: Icon(
            Icons.delete,
            color: Colors.white,
          ),
          onTap: (CompletionHandler handler) async {
            // Toast.showText('删除');
            await handler(true);
            // //根据列表下标来删除列表项
            list.removeAt(index);
            setState(() {});
          },
        ),
      ],
    );
  }
}

//单个列表项的布局
class ListItem extends StatelessWidget {
  const ListItem({
    Key key,
    this.index,
  }) : super(key: key);

  final int index;

  @override
  Widget build(BuildContext context) {
    //使用手势监测组件
    return Semantics(
      child: ExcludeSemantics(
        excluding: true,
        //添加扁平按钮控件,是为了在侧滑组件下也能显示点击态效果
        child: FlatButton(
          //此填充必须设置,否则会默认填充为16
          padding: EdgeInsets.all(0.0),
          onPressed: () {
            debugPrint('列表行点击动作在这里');
          },
          child: ListTile(
            //此填充必须设置,否则会默认填充为16
            contentPadding: EdgeInsets.all(0.0),
            leading: Column(
              //Y轴居中对齐
              mainAxisAlignment: MainAxisAlignment.center,
              //X轴左对齐
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                //插入方框容器
                Container(
                  padding: EdgeInsets.all(4.0),
                  //插入要显示的文字
                  child: Text('haha '),
                  //设置圆角背景
                  decoration: BoxDecoration(
                    //设置背景色
                    // color: Colours.active_light,
                    //设置圆角
                    borderRadius: BorderRadius.circular(6.0),
                  ),
                ),
              ],
            ),
            title: Text("bigTitle"),
            subtitle: Text("subTitle"),
            trailing: Icon(
              Icons.keyboard_arrow_right,
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by TerryLiu** [comment]
感谢回复.
我用你的页面作为主页,传入MaterialApp,然后逐条排查,发现是BotToast这个插件跟flutter_swipe_action_cell有冲突.注释掉就不报错了.

> return MaterialApp(
      title: Constant.appTitle,
//BotToast这个插件跟flutter_swipe_action_cell有冲突
//        builder: BotToastInit(),
        theme: AppTheme.lightTheme,
        onGenerateRoute:AppRoutes.router.generator,
    );

**Comment by luckysmg** [comment]
好的，我找时间去了解一下这个插件，看看冲突的地方。目前因为不是我这个框架的问题

**Comment by TerryLiu** [comment]
我打算换成oktoast再试试.
BTW: 用QQ反馈的人貌似比较少, 建议改用搞微信群

**Comment by luckysmg** [comment]
好的，感谢反馈和建议，一起加油

**Comment by TerryLiu** [comment]
改为oktoast后,还是报上述错误. 
于是我去掉了oktoast,又去掉了路由插件,直到注释掉

> theme: ThemeData(
          // 全局禁用水波纹效果
          splashFactory:const NoSplashFactory(),

才没有出现报错. 但我不能确定就只是我出现这个情况.
所以附件中我包含了NoSplashFactory这个类, 还请群主帮忙再看看.
[demo2.zip](https://github.com/luckysmg/flutter_swipe_action_cell/files/5571861/demo2.zip)

**Comment by luckysmg** [comment]
行，收到，我会尽快查看

**Comment by TerryLiu** [comment]
> 行，收到，我会尽快查看

重现时我经历了: 反复上下滑动, 点击列表项,让点击态生效(特别是末尾那几条列表数据), app置于后台,再唤起, 等等,
重现次数不止一次.

**Comment by luckysmg** [comment]
你提供的代码最好能直接让我运行，有些属性我没有弄起来就很麻烦，也不确定会不会改到你不应该让我改到的属性



发自我的iPhone


------------------ Original ------------------

**Comment by TerryLiu** [comment]
> 你提供的代码最好能直接让我运行，有些属性我没有弄起来就很麻烦，也不确定会不会改到你不应该让我改到的属性 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: terryliu <notifications@github.com&gt; Date: Fri,Nov 20,2020 3:32 PM To: luckysmg/flutter_swipe_action_cell <flutter_swipe_action_cell@noreply.github.com&gt; Cc: WenJingRui <2539699336@qq.com&gt;, Comment <comment@noreply.github.com&gt; Subject: Re: [luckysmg/flutter_swipe_action_cell] Cannot get size from a render object that has been marked dirty for layout (#12) 行，收到，我会尽快查看 重现时我经历了: 反复上下滑动, 点击列表项,让点击态生效(特别是末尾那几条列表数据), app置于后台,再唤起, 等等, 重现次数不止一次. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯, 是在你发的页面上修改的demo. 应该只需要dart文件剪贴到 lib文件夹,yaml文件覆盖下,就能跑起来

**Comment by luckysmg** [comment]
好的，我已经重现了，正在排查

**Comment by luckysmg** [comment]
貌似是因为你这个是因为上面的ItemView因为滚动出了viewport造成了回收，从而RendObject被标dirty了。但是这个时候你给的那个factory貌似会对这个renderObject进行一些操作，具体的我也不是很清楚。所以我的解决方式是：如果你不想要水波纹，那么就用GestureDetector来做点击事件，是没有水波纹的，不要用Inkwell或者ListTile，这样就可以暂时避免这个问题

**Comment by TerryLiu** [comment]
原理没太懂. 但是解决方式明白了.
