### ISSUE TITLE
[enhancement]  Reorderable Cells

### ISSUE THREAD

**Issue by daniel-lucas-silva** [luckysmg/flutter_swipe_action_cell#14]
It would be very useful to have this functionality in EDIT mode, or at least a way to add a draggable button at right side.

![image](https://user-images.githubusercontent.com/15893416/99876056-1415d100-2bd3-11eb-9f40-380986eeba23.png)

**Comment by luckysmg** [comment]
emm you can use `ReordableListView`，and use `SwipeActionCell` in `ReorderableListView`

**Comment by luckysmg** [comment]
`ReordableListView ` is support in flutter package
