### ISSUE TITLE
请教一下,长按列表项能否调用出侧滑效果?

### ISSUE THREAD

**Issue by TerryLiu** [luckysmg/flutter_swipe_action_cell#15]
首先感谢lucksmg的出色作品.
其次想请教个问题:
由于侧滑是Ios风格的操作,安卓上对应的是长按. 如果想在长按动作上也调出flutter_swipe_action_cell的侧滑效果,
需要怎么做?

**Comment by luckysmg** [comment]
emm目前只能提供交互划出，不支持编程划出，如果你要安卓的效果，那么就是在长按后弹出对话框哈哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: terryliu <notifications@github.com&gt;
发送时间: 2020年11月21日 23:06
收件人: luckysmg/flutter_swipe_action_cell <flutter_swipe_action_cell@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[luckysmg/flutter_swipe_action_cell] 请教一下,长按列表项能否调用出侧滑效果? (#15)





 
首先感谢lucksmg的出色作品.
 其次想请教个问题:
 由于侧滑是Ios风格的操作,安卓上对应的是长按. 如果想在长按动作上也调出侧滑效果,需要怎么做?

**Comment by luckysmg** [comment]
其实把交互也别定太死，长按操作个人觉得比较墨迹。。。。安卓平台的qq的消息列表不也是侧滑么hhhhhh。

**Comment by TerryLiu** [comment]
嗯,明白了.谢谢群主的秒回. 这个插件要火.

**Comment by luckysmg** [comment]
2.0.8现在已经实现，你可以在长按交互中调用 controller.openCellAt 方法
