### ISSUE TITLE
Possible to use with horizontal scrollabe Widget?

### ISSUE THREAD

**Issue by filly82** [luckysmg/flutter_swipe_action_cell#17]
great package so far, thank you !!!

I had some use cases where it perfectly suited my needs, but now I have one use case (and I think there will be some more) where I would like to have a horizontal scrollable widget (in my case it is just a ListView with scrollDirection: Axis.horizontal) and the swipe actions simultaneously. 
When arriving to the end (or beginning) of my scrollable widget I would like to show your swipe actions.

Is this (or will this ever) be possible with your package?

**Comment by luckysmg** [comment]
Maybe you can use refresh widget like “pull to refresh” or easy refresh to use a header or footer widget to be your action button.Back to your question ,everything is possible, but I don’t have much time recently .When I have time I can explore the implementation of this function 🤓🤓





发自我的iPhone


------------------ Original ------------------

**Comment by filly82** [comment]
thanks, i got it
