### ISSUE TITLE
add null-safety support

### ISSUE THREAD

**Issue by filly82** [luckysmg/flutter_swipe_action_cell#18]
since flutter stable 2.0.0 is there with stable null safety, it would be nice to have this package migrated as well

**Comment by luckysmg** [comment]
Null safety is on the way.😀

**Comment by luckysmg** [comment]
Null safety is available on v2.0.0 😀 ，you can try it😁.
If there are any bugs,plz contact me😁
.

**Comment by filly82** [comment]
works fine with me and my use-cases. thanks.
closing this then
