### ISSUE TITLE
如何点击空白处隐藏滑动出来的删除按钮

### ISSUE THREAD

**Issue by niyangup** [luckysmg/flutter_swipe_action_cell#2]
以最简单的删除demo为例，当删除按钮滑动出来了，我又不想删除了，能否点击空白处让删除自己滑回去

**Comment by luckysmg** [comment]
目前没有做这个，因为感觉意义不大，可以通过滑动列表来关闭，emm其实没有很理解这个需求的意义，微信的侧滑有做这个功能吗？

**Comment by luckysmg** [comment]
因为我没办法监听到其他地方的点击事件

**Comment by niyangup** [comment]
android版本QQ的消息列表上有这个功能，另外如何通过滑动列表来关闭

**Comment by luckysmg** [comment]
这个应该是QQ定制的，因为你其他的cell内部自己定义的点击事件我捕获不到。。。不过后续我可以提供一个API让你去发出一个让所有cell关闭的事件，然后你自己在你自己的内容点击的时候根据我提供的API发一个事件，拉出的cell就可以关掉了，不过这样侵入性很强。。。

**Comment by niyangup** [comment]
可以的哥

**Comment by luckysmg** [comment]
行，后续我会增加一些API，请关注后续版本

**Comment by niyangup** [comment]
太对了哥 哥太对

**Comment by luckysmg** [comment]
已经在版本1.0.5+1中添加，具体使用方法就用SwipeActionEditController con = SwipeActionEditController()
调用
con.closeAllOpenCell();
这个controller可以不传入cell，但是如果要用编辑模式就需要传入cell中

**Comment by niyangup** [comment]
非常的棒棒  射射哥
