### ISSUE TITLE
插件会把SwipeActionCell -> child里的圆角去掉，会导致无法设置圆角

### ISSUE THREAD

**Issue by fuyunmanbu** [luckysmg/flutter_swipe_action_cell#22]
如标题所示，你可以试试

**Comment by luckysmg** [comment]
了解，我复现一下

**Comment by luckysmg** [comment]
可以加圆角啊，没问题啊，版本2.0.3
```dart
return SwipeActionCell(
            key: ValueKey(list[index]),
            leadingActions: [
              SwipeAction(
                nestedAction: SwipeNestedAction(title: "确认删除"),
                title: "删除",
                onTap: (handler) async {
                  await handler(true);
                  list.removeAt(index);
                  setState(() {});
                },
              ),
              SwipeAction(
                color: Colors.orange,
                title: "置顶",
                onTap: (handler) async {
                  await handler(true);
                  list.removeAt(index);
                  setState(() {});
                },
              ),
            ],
            trailingActions: [
              SwipeAction(
                title: "删除",
                nestedAction: SwipeNestedAction(title: "确认删除"),
                onTap: (handler) async {
                  await handler(true);
                  list.removeAt(index);
                  setState(() {});
                },
              ),
              SwipeAction(
                color: Colors.orange,
                title: "置顶",
                onTap: (handler) async {
                  await handler(false);
                },
              ),
            ],
            child: Container(
              decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(20), color: Colors.red),
              padding: const EdgeInsets.all(8.0),
              child: DecoratedBox(
                decoration: BoxDecoration(borderRadius: BorderRadius.circular(20),color: Colors.blue),
                child: Text("这是第：${list[index]}个列表项",
                    style: TextStyle(fontSize: 25)),
              ),
            ),
          );

```

**Comment by fuyunmanbu** [comment]
```
  itemBuilder: (ctx, index) {
    return SwipeActionCell(
      key: ValueKey(index),
      performsFirstActionWithFullSwipe: false,
      trailingActions:<SwipeAction>[
        SwipeAction(
            title: "删除",
            widthSpace: 150.w,
            forceAlignmentToBoundary: true,
            nestedAction: SwipeNestedAction(title: "确认删除"),
            style: Constants.textSize14.copyWith(
              color: Colors.white
            ),
            onTap: (CompletionHandler handler) {

            },
            color: Colours.red
        ),
        SwipeAction(
            title: "编辑",
            widthSpace: 150.w,
            forceAlignmentToBoundary: true,
            style: Constants.textSize14.copyWith(
                color: Colors.white
            ),
            onTap: (CompletionHandler handler) {

            },
            color: Colours.app_main
        ),
      ],
      child: Container(
        decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(20), color: Colors.red),
        padding: const EdgeInsets.all(8.0),
        child: DecoratedBox(
          decoration: BoxDecoration(borderRadius: BorderRadius.circular(20),color: Colors.blue),
          child: Text("这是第：${index}个列表项",
              style: TextStyle(fontSize: 25)),
        ),
      ),
    );
  },
```

![Snip20210420_63](https://user-images.githubusercontent.com/16368126/115362722-68f65b80-a1f4-11eb-82ab-94a7393f67a8.png)

**Comment by fuyunmanbu** [comment]
外面还有一层白的，导致无法设置圆角阴影，谢谢🙏

**Comment by luckysmg** [comment]
你给我一个demo code吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: fuyunmanbu ***@***.***&gt;
发送时间: 2021年4月20日 16:23
收件人: luckysmg/flutter_swipe_action_cell ***@***.***&gt;
抄送: WenJingRui ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[luckysmg/flutter_swipe_action_cell] 插件会把SwipeActionCell -&gt; child里的圆角去掉，会导致无法设置圆角 (#22)





 
外面还有一层白的，导致无法设置圆角阴影，谢谢🙏

**Comment by fuyunmanbu** [comment]
flutter 2.0.3
这是一个可以运行的简单demo




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "luckysmg/flutter_swipe_action_cell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月20日(星期二) 下午4:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [luckysmg/flutter_swipe_action_cell] 插件会把SwipeActionCell -&gt; child里的圆角去掉，会导致无法设置圆角 (#22)





 你给我一个demo code吧 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: fuyunmanbu ***@***.***&amp;gt; 
 发送时间: 2021年4月20日 16:23 
 收件人: luckysmg/flutter_swipe_action_cell ***@***.***&amp;gt; 
 抄送: WenJingRui ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 主题: 回复：[luckysmg/flutter_swipe_action_cell] 插件会把SwipeActionCell -&amp;gt; child里的圆角去掉，会导致无法设置圆角 (#22) 
 
 
 
 
 
   
 外面还有一层白的，导致无法设置圆角阴影，谢谢🙏 
   
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

exam.zip (102.70M, 2021年05月20日 18:21 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=04383835b6fba0ca2a6dc1741f36061c000a5a0158045601145b0f540c1b0006085d150c0802051e5f5d0a030d0f50515c095e02393e34564159551b435f443304&code=98859643

**Comment by luckysmg** [comment]
您这个问题我看了，具体问题的原因在于内部用了`SizeTransition`,而这个控件内部有一个ClipRect会导致这个问题，但是删除动画需要用`SizeTransition`来完成，所以目前解决方案是：你修改cell的源码，去掉`SizeTransition`这一层，对应地，你将不能使用删除动画。我以后有时间会探索其他解决方案，目前可能只能这样

**Comment by fuyunmanbu** [comment]
非常感谢，麻烦你了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WenJingRui ***@***.***&gt;
发送时间: 2021年4月20日 21:24
收件人: luckysmg/flutter_swipe_action_cell ***@***.***&gt;
抄送: fuyunmanbu ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[luckysmg/flutter_swipe_action_cell] 插件会把SwipeActionCell -&gt; child里的圆角去掉，会导致无法设置圆角 (#22)
