### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: LateInitializationError: Field 'offsetFillActionContentCurve' has not been initialized.

### ISSUE THREAD

**Issue by naamapps** [luckysmg/flutter_swipe_action_cell#25]
I get this error sometimes when tapping on an action with nested action.

`[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: LateInitializationError: Field 'offsetFillActionContentCurve' has not been initialized.`

**Comment by luckysmg** [comment]
emm The nestedAction param is only support for the first action now,so dont use nestedAction on any action which is not first action...

**Comment by naamapps** [comment]
Hey @luckysmg, I did use it on the first action.
I have a total of 3 actions. When tapping the first the nested action sometimes throws this error and sometimes not. When it throws the error, the nested action doesn't animated and stays the same width as the main action.

**Comment by luckysmg** [comment]
emm could you give me a demo code? Just the code of your cell layout

**Comment by naamapps** [comment]
@luckysmg, it's like example 7 in the Readme, just with one more action at the end and a check if the list have more than one item enable the nested action on the first action (because I don't want to remove an item if it is the only item on the list) - maybe that is the issue.

It's like this:
`nestedAction: list.length == 1? null: SwipeNestedAction(...) 
`

**Comment by naamapps** [comment]
Hi, I am still getting this error in the new version.
It is pretty hard to replicate and it's really random.

Please try to solve this,
Thank you

**Comment by luckysmg** [comment]
Ok,i got this

**Comment by luckysmg** [comment]
I didn't reproduce .... could you give me your demo code or give me the video about how you operate this cell ?

**Comment by naamapps** [comment]
https://user-images.githubusercontent.com/37176893/116565834-e023a200-a90e-11eb-9023-a3a66ce7b94a.mp4


https://user-images.githubusercontent.com/37176893/116565842-e1ed6580-a90e-11eb-90ad-944a70c5e215.mp4


In the first video, I found another bug, where the nested action opens when the cell closes (you need to be very quick to get to this).

In the second video, this is where the error occurrs.
Also in this you need to be quick, 

Steps to reproduce:
1. Add an item
2. At the same time the new items animates, open the first item cell and try to delete
3. Error occurs Or successfully opens nested action (the error sometimes doesn't happen)

Hope that helps, 
Thanks

**Comment by luckysmg** [comment]
got it

**Comment by luckysmg** [comment]
could you give me your cell code?

**Comment by naamapps** [comment]
```
final slideActions = [
                SwipeAction(
                  nestedAction: list.length == 1
                      ? null
                      : SwipeNestedAction(
                          content: Container(
                            margin: const EdgeInsetsDirectional.only(start: 10),
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(30),
                              color: Colors.redAccent,
                            ),
                            width: 180,
                            height: 50,
                            child: OverflowBox(
                              maxWidth: double.infinity,
                              child: Row(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: [
                                  const Icon(
                                    Icons.delete,
                                    color: Colors.white,
                                  ),
                                  Text(
                                    '${'delete'.tr()}?',
                                    style: const TextStyle(
                                      color: Colors.white,
                                      fontSize: 18,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                  color: Colors.transparent,
                  widthSpace: 60,
                  content: _getIconButton(
                    list.length > 1
                        ? Colors.redAccent
                        : Theme.of(context).appBarTheme.color,
                    Icons.delete,
                    list.length > 1
                        ? Colors.white
                        : Theme.of(context).colorScheme.onSecondary,
                  ),
                  onTap: (handler) {
                    if (list.length > 1) {
                      model.deleteItem(index);
                      handler(false);
                    }
                  },
                ),
                SwipeAction(
                  widthSpace: 60,
                  content: _getIconButton(
                    Colors.orange[300],
                    Icons.add,
                    Colors.white,
                    30,
                  ),
                  color: Colors.transparent,
                  onTap: (handler) {
                    model.addItemBelow(index, context);
                    handler(false);
                  },
                ),
                SwipeAction(
                  widthSpace: 60,
                  content: _getIconButton(
                    Colors.blue[300],
                    MdiIcons.linkVariant,
                    Colors.white,
                    30,
                  ),
                  color: Colors.transparent,
                  onTap: (handler) {
                    handler(false);
                  },
                ),
              ];
```

**Comment by naamapps** [comment]
I use this package for the list: https://pub.dev/packages/implicitly_animated_reorderable_list

**Comment by luckysmg** [comment]
About first bug you said I have reproduce...your finger is really...emmm magic quick.......But I think I can handle this..


About second ,you can just operate your model without call hander(false),because if you call handler(false),I will close this cell with animation,which may cause some issue....especially when you use another list package...so you can try not to call hander(false)

**Comment by naamapps** [comment]
Just to make sure, what did you reproduce? the error (the nested doesn't open) or the one where the nested opens when the cell closes

**Comment by luckysmg** [comment]
the one where the nested opens when the cell closes

**Comment by naamapps** [comment]
You didn't succeed to reproduce the error? This is actually my main concern

**Comment by luckysmg** [comment]
emm could you give a  min reproduceable demo code with the package you said?

**Comment by naamapps** [comment]
I don't think it's connected to the package.
The error says that the offsetFillActionContentCurve field is not initialized.
My guess is that somewhere in the code the field is not initialized.

Can you try and add maybe a bool field `disabled` in the `SwipeNestedAction`?
I really think that when I give null to the nested action and then give it a value, it breaks something.
So maybe adding a disabled field to disable the nested action might solve this issue.

**Comment by luckysmg** [comment]
emm thx,I try to solve this

**Comment by luckysmg** [comment]
you can try this ref`4eb537721e2c23794227cf6c084882745a4b7251`

**Comment by naamapps** [comment]
Sure, couple of minutes

**Comment by luckysmg** [comment]
It that ok  ?

**Comment by naamapps** [comment]
It's working!!
Thank you, really appreciate it man !

**Comment by luckysmg** [comment]
ok,i will fix your second bug,and i will push 2.0.7,when I complete, i will tell you 😀

**Comment by luckysmg** [comment]
I have pushed 2.0.6 to pub.dev,,maybe available after couple of minutes..You can try...And hoping the star from you hahaha

**Comment by luckysmg** [comment]
If there is not problem ,you can close this issue😀

**Comment by naamapps** [comment]
Everything works perfect!
You earned a star buddy 👍 
Thanks again
