### ISSUE TITLE
Can I open the SwipeAction programmatically?

### ISSUE THREAD

**Issue by konnanl** [luckysmg/flutter_swipe_action_cell#26]
I would like to open the SwipeAction programmatically and without animation, any suggestion on it?

**Comment by luckysmg** [comment]
At present,I have not provided this function yet,maybe I will think give a thought to developing this function

**Comment by luckysmg** [comment]
Hi, you can try `2.0.8`, use `controller.openCellAt`

**Comment by luckysmg** [comment]
If there is no problem,I close this issue.You can reopen it whenever you have problem
