### ISSUE TITLE
如何实现右上和右下圆角？

### ISSUE THREAD

**Issue by Allen5** [luckysmg/flutter_swipe_action_cell#27]
hello，先感谢老哥贡献组件。看到参数中有 backgroundRadius 参数，是实现左上和左下圆角的，貌似也是默认行为。

请问如何实现右上和右下圆角？

**Comment by luckysmg** [comment]
最新版本应该这个参数支持按钮所有圆角的吧

**Comment by luckysmg** [comment]
试试最新版本

**Comment by Allen5** [comment]
尝试了下，貌似还是不行

图片传不上去，我贴下代码和版本信息：

代码：
 trailingActions: [
            SwipeAction(
              color: FlowPrimaryColor,
              backgroundRadius: 5.0,
              content: Container(
                child: Icon(
                  Icons.delete,
                  color: FlowReverseStandColor,
                  size: 32,),
                ),
              widthSpace: 60,
              forceAlignmentToBoundary: true,
              onTap: (handler) async {
                print("onTap");
              }),
          ],

版本：
flutter_swipe_action_cell:
    dependency: "direct main"
    description:
      name: flutter_swipe_action_cell
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "2.1.0"

**Comment by luckysmg** [comment]
有反应的啊，你设置成20看看，

**Comment by Allen5** [comment]
<img width="348" alt="image" src="https://user-images.githubusercontent.com/10849348/118242124-8e167b00-b4cf-11eb-9815-a65f448a7e97.png">

效果还是左上和左下的。 额，我是想实现右上和右下，左上和左下不带圆角的

**Comment by luckysmg** [comment]
哦哦你是这个意思，这个圆角我是是四周全部给的hhhhhh，你拉到最右侧就能看到另外的圆角了hhhhhh

**Comment by luckysmg** [comment]
你这个按钮在右侧。。不应该要右侧圆角么

**Comment by Allen5** [comment]
是的，我是想要右侧圆角。然后backgroundRadius传入之后是左侧的。不知道如何实现了

**Comment by luckysmg** [comment]
那么你可以利用action的content属性哈，这样你就可以自定义里面的样式了

**Comment by Allen5** [comment]
OK，我试试。看看后续是否可以升级成backgroundRadius传入 BorderRadius的属性哈？这样可以简单的传入自定义的了

**Comment by luckysmg** [comment]
这个因为内部的布局原理问题暂时不考虑

**Comment by luckysmg** [comment]
可以实现吗

**Comment by luckysmg** [comment]
如果没问题的话就关了哈，有问题可以随时reopen

**Comment by Allen5** [comment]
好的，用content的圆角会被外面一层盖住哈。没有成功。

**Comment by luckysmg** [comment]
参考一下exmaple代码

**Comment by Allen5** [comment]
好的

**Comment by luckysmg** [comment]
Example 8 仿微信的那个

**Comment by Allen5** [comment]
好的，3KS
