### ISSUE TITLE
当trailingActions个数为一个的时候，删除按钮侧滑不能完全展示

### ISSUE THREAD

**Issue by LDreame** [luckysmg/flutter_swipe_action_cell#28]
![截屏2021-05-17 下午4 42 01](https://user-images.githubusercontent.com/16238714/118459941-cff12c80-b72e-11eb-820d-2a19f6240519.png)

![截屏2021-05-17 下午4 42 21](https://user-images.githubusercontent.com/16238714/118459995-dc758500-b72e-11eb-8ae4-d82fb905644b.png)

Widget _item(BuildContext ctx, int index) {
    return SwipeActionCell(
      controller: controller,
      index: index,
      key: ValueKey(list[index]),

      ///animation default value below...
      normalAnimationDuration: 500,
      deleteAnimationDuration: 400,
      performsFirstActionWithFullSwipe: true,
      trailingActions: [
        SwipeAction(
            title: "取消删除",
            // nestedAction: SwipeNestedAction(title: "confirm"),
            onTap: (handler) async {
              await handler(true);

              list.removeAt(index);
              setState(() {});
            }),
        // SwipeAction(title: "action2", color: Colors.grey, onTap: (handler) {}),
      ],

action数组为一个的时候 取消删除 显示不完整

**Comment by LDreame** [comment]
这个如果是大于一个的时候是不需要设置宽度的，这个是什么原因呢

**Comment by luckysmg** [comment]
都要设置啊，因为目前因为需要计算每个按钮的宽度，所以需要显式的指定每个按钮的宽度

**Comment by luckysmg** [comment]
按钮分为两种，以右边拉出的按钮为例，分为跟随和不跟随的两种按钮，跟随的意思就是按钮中的内容（比如文字）会不会完全跟随手指移动，当只有一个按钮，并且`performsFirstActionWithFullSwipe` 为true，并且此`SwipeAction`的`forceAlignmentToBoundary`为false的时候，才会生成非跟随按钮，其他情况均生成跟随按钮。你可以试试

**Comment by luckysmg** [comment]
如果还有问题随时reopen
