### ISSUE TITLE
Phone freeze and have to restart 

### ISSUE THREAD

**Issue by naamapps** [luckysmg/flutter_swipe_action_cell#29]
Hey,
It's me again :)
I sometime encounter a weird behaviour with your package.
It is working as expected most of the times, but one time out of hundred when trying to open a cell it freezes my phone and I have to hard reset.

It is not happening anywhere in my app, except when trying to open a cell, that is why I think it is something to do with your package.

Is there anything that may cause a deadlock or a loop that never ends? 
I don't have any logs to give because it is really random.

Please help,
Thank you!

**Comment by luckysmg** [comment]
No loops or deadlock,here is the whole process
1.When you open cell,you will call`controller.openCellAt`method,and will call 
```dart
SwipeActionStore.getInstance().bus.fire(CellProgramOpenEvent(
        index: index, trailing: trailing, animated: animated));
```
internally.

2. In every cell,it has a event subscription to listen this event incoming,if the `index` == `widget.index`,it will execute the open animation

So i think it is ok......

You can give me a demo code to reproduce the bug....I can't reproduce the bug you said😟😟

**Comment by naamapps** [comment]
Hey @luckysmg, I meant opening a cell via finger.
It freezes exactly at the moment I swipe to open. 

I am not talking about opening a cell via the controller.

It's so random that I just sometimes play with my app to see everything is fine, and I get to the section where I use your package, trying to open a cell with finger and then it freezes.
No errors, no logs, nothing. 

Hope you can find the issue 😔

**Comment by luckysmg** [comment]
Could you find this issue in my `example`? If not ,try to find the difference between your app and my `example`app.....Or you can provide a demo code to me to reproduce the issue........
