### ISSUE TITLE
能否根据设置禁用左侧滑动行为，否则页面左侧滑动会影响原有的左侧滑动后退功能。十分感谢。

### ISSUE THREAD

**Issue by sarins** [luckysmg/flutter_swipe_action_cell#30]
RT

**Comment by luckysmg** [comment]
这个类似iOS的从左侧右滑返回的效果，我这个cell应该是不会影响的哈

https://user-images.githubusercontent.com/49340347/122911384-d1df8880-d389-11eb-9781-1ee31c579c64.mov

**Comment by luckysmg** [comment]
还有什么问题嘛？没有问题的话关issue了哈

**Comment by sarins** [comment]
十分感谢回复，我再调试一下。我这边是android环境调试的。
@luckysmg 您这个示例代码能否共享一下？

**Comment by luckysmg** [comment]
example就是



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Axl Zhao ***@***.***&gt;
发送时间: 2021年6月25日 12:56
收件人: luckysmg/flutter_swipe_action_cell ***@***.***&gt;
抄送: WenJingRui ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[luckysmg/flutter_swipe_action_cell] 能否根据设置禁用左侧滑动行为，否则页面左侧滑动会影响原有的左侧滑动后退功能。十分感谢。 (#30)





 
十分感谢回复，我再调试一下。我这边是android环境调试的。
 @luckysmg 您这个示例代码能否共享一下？

**Comment by sarins** [comment]
@luckysmg OK，那我再仔细看看，十分感谢。

**Comment by sarins** [comment]
@luckysmg 已经验证好了，需要在外层容器边框处保留一定的空白，否则被列表项遮挡后就不能触发到边框的返回事件了。

**Comment by luckysmg** [comment]
我exmaple里面貌似也没有加空白也没问题吧。。。。

**Comment by luckysmg** [comment]
你说的外层容器是ListView吗？

**Comment by sarins** [comment]
对的。我就是给外层ListView加上了Padding，因为我的ListView到屏幕之间之前是没有间隙的

**Comment by sarins** [comment]
我用的是android设备，不知道是不是和ios模拟器有所区别。

**Comment by luckysmg** [comment]
奇怪，我的example貌似没有padding也是正常的hhhhhhhhhh

**Comment by luckysmg** [comment]
有可能是安卓和iOS的差异

**Comment by sarins** [comment]
OK, 感谢这个开源，给我们帮助了很多，把经验分享出来，也许对以后使用的朋友会有帮助。

**Comment by luckysmg** [comment]
感谢支持😀

**Comment by luckysmg** [comment]
这里我用安卓的试了一下，的确也没问题，可能是您的代码和我的哪里不一样哈，您可以比对比对


https://user-images.githubusercontent.com/49340347/123393820-0e50f580-d5d1-11eb-9817-ebc8f86cd9db.mov
