### ISSUE TITLE
只要编辑功能，怎么禁掉左滑，和basepage的tabpage左滑冲突了

### ISSUE THREAD

**Issue by DanielYK** [luckysmg/flutter_swipe_action_cell#4]
你好 只要编辑功能，怎么禁掉左滑，和basepage的tabpage左滑冲突了

**Comment by luckysmg** [comment]
之前没有想到这个需求，马上在后续版本中推出，请持续关注

**Comment by luckysmg** [comment]
我已经在最新版本中增加了 isDraggble参数，因为考虑到你只用编辑功能，所以也允许不传入actions参数，你可以将isDraggble 设置为false，这样你就可以只用编辑模式而不用侧滑了。。。这个issue我先关闭了，如果您测试下来还有问题，欢迎您重新打开此issue
