### ISSUE TITLE
请问使用 openCellAt 有什么需要注意的地方吗

### ISSUE THREAD

**Issue by zhxst** [luckysmg/flutter_swipe_action_cell#43]

**Comment by zhxst** [comment]
我参考了项目的example，向`SwipeActionCell`传入了controller，index，以及ValueKey(item)。
但是使用`openCellAt`时没有效果，而`closeAllOpenCell`是有效的。
所以请问要想`openCellAt`有什么需要注意的地方吗？谢谢。

**Comment by luckysmg** [comment]
example能打开cell吗



发自我的iPhone


------------------ Original ------------------
From: zhxst ***@***.***&gt;
Date: Mon,Apr 25,2022 8:20 PM
To: luckysmg/flutter_swipe_action_cell ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [luckysmg/flutter_swipe_action_cell] What (Issue #43)





 
我参考了项目的example，向SwipeActionCell传入了controller，index，以及ValueKey(item)。
 但是使用openCellAt时没有效果，而closeAllOpenCell是有效的。
 所以请问要想openCellAt有什么需要注意的地方吗？谢谢。

**Comment by zhxst** [comment]
example可以打开

**Comment by luckysmg** [comment]
那还说啥，当然是找你的代码和example的区别不就得了😂



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhxst ***@***.***&gt;
发送时间: 2022年4月26日 08:41
收件人: luckysmg/flutter_swipe_action_cell ***@***.***&gt;
抄送: WenJingRui ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [luckysmg/flutter_swipe_action_cell] 请问使用 openCellAt 有什么需要注意的地方吗 (Issue #43)





 
example可以打开

**Comment by zhxst** [comment]
我就想问下这个openCellAt找到对应的cell去打开需要什么条件，或者是通过什么去检查cell的

**Comment by luckysmg** [comment]
啥意思，你是问使用方法还是说技术原理



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhxst ***@***.***&gt;
发送时间: 2022年4月26日 09:17
收件人: luckysmg/flutter_swipe_action_cell ***@***.***&gt;
抄送: WenJingRui ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [luckysmg/flutter_swipe_action_cell] 请问使用 openCellAt 有什么需要注意的地方吗 (Issue #43)





 
我就想问下这个openCellAt找到对应的cell去打开需要什么条件，或者是通过什么去检查cell的

**Comment by zhxst** [comment]
就是简单介绍一下，这个openCellAt是通过什么来找到cell的，我就好检查我的代码，到底是啥问题
