### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by Ilya-Vysotsky** [luckysmg/flutter_swipe_action_cell#44]
When i scroll ListView.builder than each new appears item triggers rebuild all of SvipeActionCell widgets.(9-15 pcs per time). is this behavior right and expected? 
![Screenshot 2022-05-04 at 17 09 12](https://user-images.githubusercontent.com/90622492/166699242-1aec4cd0-fde3-4509-a5fb-6949b67ddfaa.png)
When i remove SwipeActionCell widget, yhen builder builds only new IgnorePointer. What is my bad?
I tried to pass index as ValueKey, it doesn't help.

**Comment by luckysmg** [comment]
No ,when scroll,the existing widget will not rebuild.Moreover,the key should not be `ValueKey(index)`.
It should be `ValueKey(yourDataList[index])`. You can check the example project in this repo.

**Comment by luckysmg** [comment]
Fixed.You can check the new version on `pub.dev` with `2.2.1`. You can close this issue after testing good on your code😀.

**Comment by Ilya-Vysotsky** [comment]
Thank you, it good in my code!)
