### ISSUE TITLE
可以添加左侧拉出的功能吗，这样可能看起来比较完整

### ISSUE THREAD

**Issue by huanghui1998hhh** [luckysmg/flutter_swipe_action_cell#5]
我尝试过修改您的代码 但由于是初学者实现的并不完美

**Comment by luckysmg** [comment]
感谢您的建议，
我的个人观点如下：说实话个人觉得左边的不太实用，所以开发的时候没考虑适配左侧拉出的。我偏向于实用性，而不是看起来怎么怎么样hhhhhhhhhhhh，您可以尝试修改。以后我可能会考虑适配，因为这个库还很年轻，刚出不久，我目前的打算是先稳定已有的API以及等待所有的已有API的功能都稳定且无bug后再去开发新的功能，所以我以后可能会考虑开发左侧拉出的，但是不一定会哈哈哈哈哈

**Comment by huanghui1998hhh** [comment]
好的 感谢回复~

**Comment by luckysmg** [comment]
此功能目前已经排上日程，正在努力开发中

**Comment by PatrickChoo** [comment]
左右侧能拉出按钮还是非常实用的，在iOS信息、邮件、备忘录都用到，左右侧作不同的功能组分区，比较常见在生产力工具。期待更新👏👍

**Comment by luckysmg** [comment]
目前已经推送到了v1.1.2版本中，所有右边按钮支持的交互左边也都支持。目前还没有确定交互逻辑是否稳定无bug，你们可以先尝尝鲜。  @PatrickChoo @huanghui1998hhh

**Comment by PatrickChoo** [comment]
> 目前已经推送到了v1.1.2版本中，所有右边按钮支持的交互左边也都支持。目前还没有确定交互逻辑是否稳定无bug，你们可以先尝尝鲜。 @PatrickChoo @huanghui1998hhh

🚀 惊叹火箭速度！

**Comment by luckysmg** [comment]
已经实现，请在1.2.1版本中使用
