### ISSUE TITLE
Use AlertDialog in nestedAction

### ISSUE THREAD

**Issue by Amirnlz** [luckysmg/flutter_swipe_action_cell#50]
I have to implement a some custom widget like AlertDialog  to show user that is she/he sure to cancel the order or not.
But the problem is the width and height of the dialog is bounded with SwipeAction -> widthSpace, width and height is bounded by parent height. So can't showDialog and will cause overflow.

**Comment by luckysmg** [comment]
AlertDialog is in screen, Why is releated with SwipeActionCell?

**Comment by Amirnlz** [comment]
I was doing wrong, I tried to show dialog with nestedAction -> content that cause overflow, now I do it with another method.
```dart
 onTap: (CompletionHandler handler) async {
            final removeOrder = await confirmToRemove();
            await handler(removeOrder!);
            ...
}
```

**Comment by luckysmg** [comment]
Closing this issue
