### ISSUE TITLE
在gridview中进行删除操作，sizeTransition异常，cell被红色填充

### ISSUE THREAD

**Issue by w467364316** [luckysmg/flutter_swipe_action_cell#51]
版本信息如下：
flutter: 2.0.4
dart: 2.12.2
flutter_swipe_action_cell: ^2.2.0

现象：
在gridview.count中使用swipeActionCell，侧滑删除后，红色覆盖整个cell，但是不会发生形变（移除效果动画）。

https://user-images.githubusercontent.com/15647680/191155292-ef1a0698-d608-4429-8b79-802ca3e4ae46.mp4

**Comment by luckysmg** [comment]
这个对标的是iOS原生的删除效果，对标iOS UITableView的`UISwipeActionsConfiguration`，从对标设计上看就没打算给GridView（类似iOS原生`UICollectionView`）用，本身是给ListView或者SliverList用的（ListView和SliverList类似iOS原生的`UITableView`）
