### ISSUE TITLE
scrollPosition = Scrollable.maybeOf(context)?.position;

### ISSUE THREAD

**Issue by suyie001** [luckysmg/flutter_swipe_action_cell#56]
There is no maybeOf method in Scrollable. 

line 434 in cell.dart:
scrollPosition = Scrollable.maybeOf(context)?.position;

should be :
scrollPosition = Scrollable.of(context)?.position;

**Comment by luckysmg** [comment]
For flutter 3.7before， use3.0.7

**Comment by suyie001** [comment]
Thanks.

**Comment by knight0zh** [comment]
这个我问题修复了吗  我用了  flutter_swipe_action_cell: ^3.1.0，遇到了这个问题
