### ISSUE TITLE
cell expanding when used with tab bar

### ISSUE THREAD

**Issue by SomeoneAndNoone** [luckysmg/flutter_swipe_action_cell#57]
<img src="https://user-images.githubusercontent.com/50243010/220176591-e2246022-0b39-4bf8-b4c2-de3f9ce3386b.gif" width="40%" height="40%"/>

When I use swipe cell for tab bar with 3 screens, the action cell is expanding unexpectedly when I swipe(by tapping) to the third cell in particular. It is working as expected if I disable page transition animation on TabController. When sliding manually, everything is fine

**Comment by luckysmg** [comment]
Plz provide a demo code to reproduce this issue here.

**Comment by SomeoneAndNoone** [comment]
class _MyGoalsScreenStates extends State<MyGoalsScreen> with SingleTickerProviderStateMixin {
  late MyGoalsBloc bloc;
  late final TabController controller;

  @override
  void initState() {
    super.initState();
    bloc = MyGoalsBloc(context.read<GoalsRepository>());
    controller = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    bloc.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return BlocProvider.value(
      value: bloc,
      child: BlocConsumer<MyGoalsBloc, MyGoalsState>(
          listener: (_, state) {},
          builder: (context, state) {
            if (state is MyGoalsLoadedState) {
              return Scaffold(
                appBar: AppBar(
                  bottom: TabBar(
                    onTap: (int) {},
                    controller: controller,
                    tabs: [
                      Tab(text: S.of(context).all),
                      Tab(text: S.of(context).toDo),
                      Tab(text: S.of(context).finished),
                    ],
                  ),
                  title: SectionHeader(title: S.of(context).myGoals, left: false),
                ),
                body: SafeArea(
                  child: TabBarView(
                    controller: controller,
                    children: [
                      WidgetWithSwipeCards(),
                      WidgetWithSwipeCards(),
                      WidgetWithSwipeCards(),
                    ],
                  ),
                ),
              );
            }

            return Scaffold(
              body: SafeArea(
                child: Column(
                  children: [
                    SectionHeader(title: S.of(context).myGoals),
                    Expanded(
                      child: Center(
                        child: CircularProgressIndicator(),
                      ),
                    )
                  ],
                ),
              ),
            );
          }),
    );
  }
}

**Comment by SomeoneAndNoone** [comment]
@luckysmg have you resolved it already? Sorry for late response. I found a workaround but it is not expected solution. Here is the demo code if you need:

`class _MyGoalsScreenStates extends State<MyGoalsScreen> with SingleTickerProviderStateMixin {
  late MyGoalsBloc bloc;
  late final TabController controller;

  @override
  void initState() {
    super.initState();
    bloc = MyGoalsBloc(context.read<GoalsRepository>());
    controller = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    bloc.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return BlocProvider.value(
      value: bloc,
      child: BlocConsumer<MyGoalsBloc, MyGoalsState>(
          listener: (_, state) {},
          builder: (context, state) {
            if (state is MyGoalsLoadedState) {
              return Scaffold(
                appBar: AppBar(
                  bottom: TabBar(
                    onTap: (int) {},
                    controller: controller,
                    tabs: [
                      Tab(text: S.of(context).all),
                      Tab(text: S.of(context).toDo),
                      Tab(text: S.of(context).finished),
                    ],
                  ),
                  title: SectionHeader(title: S.of(context).myGoals, left: false),
                ),
                body: SafeArea(
                  child: TabBarView(
                    controller: controller,
                    children: [
                      WidgetWithSwipeCards(),
                      WidgetWithSwipeCards(),
                      WidgetWithSwipeCards(),
                    ],
                  ),
                ),
              );
            }

            return Scaffold(
              body: SafeArea(
                child: Column(
                  children: [
                    SectionHeader(title: S.of(context).myGoals),
                    Expanded(
                      child: Center(
                        child: CircularProgressIndicator(),
                      ),
                    )
                  ],
                ),
              ),
            );
          }),
    );
  }
}
`

**Comment by SomeoneAndNoone** [comment]
Tab controller:
`
controller = TabController(length: 3, vsync: this);
`
