### ISSUE TITLE
刚开始时leadingActions为空的，再设置后滑不出来

### ISSUE THREAD

**Issue by shawn736** [luckysmg/flutter_swipe_action_cell#59]
你好，这个库的侧滑效果很不错，👍。
遇到了一个问题，如下：
刚开始时leadingActions为空的，然后有一个开关触发，设置了leadingActions，结果无法滑出来；
如果刚开始leadingActions不为空，接着设置为空，然后再设置leadingActions，就可以滑出来。
下面的代码，是在example项目基础上增加了一个isHaveLeading，通过这个参数，来控制leadingActions的显示。

  bool isHaveLeading = false;

  Widget _item(BuildContext ctx, int index) {

    List<SwipeAction>? leadingActions;
    if (isHaveLeading) {
      leadingActions = [
        SwipeAction(
            title: "delete",
            onTap: (handler) async {
              await handler(true);
              list.removeAt(index);
              setState(() {});
            }),
        SwipeAction(
            title: "action3", color: Colors.orange, onTap: (handler) {}),
      ];
    }

    return SwipeActionCell(
      controller: controller,
      index: index,

      // Required!
      key: ValueKey(list[index]),

      // Animation default value below
      // normalAnimationDuration: 400,
      // deleteAnimationDuration: 400,
      selectedForegroundColor: Colors.black.withAlpha(30),
      trailingActions: [
        SwipeAction(
            title: "delete",
            performsFirstActionWithFullSwipe: true,
            nestedAction: SwipeNestedAction(title: "confirm"),
            onTap: (handler) async {
              await handler(true);

              list.removeAt(index);
              setState(() {});
            }),
        SwipeAction(title: "action2", color: Colors.grey, onTap: (handler) {}),
      ],
      leadingActions: leadingActions,
      child: GestureDetector(
        onTap: () {
          Navigator.push(
              context, CupertinoPageRoute(builder: (ctx) => const HomePage()));
        },
        child: Padding(
          padding: const EdgeInsets.all(20.0),
          child: Text("This is index of ${list[index]}",
              style: const TextStyle(fontSize: 30)),
        ),
      ),
    );
  }

**Comment by luckysmg** [comment]
`3.1.1` 版本已修复

**Comment by shawn736** [comment]
> `3.1.1` 版本已修复

赞👍，已微信支持。
