### ISSUE TITLE
in Flutter 1.22 overflow argument not exist anymore.

### ISSUE THREAD

**Issue by play0sm** [luckysmg/flutter_swipe_action_cell#6]
https://github.com/luckysmg/flutter_swipe_action_cell/blob/8bcfedc0765a63a84f0cc35359fa9f9838979a43/lib/core/cell.dart#L651

**Comment by luckysmg** [comment]
Thx,I have received your issue,and i will handle it as soon as I can

**Comment by play0sm** [comment]
> What's your swipe_action_cell version?

1.0.8

**Comment by luckysmg** [comment]
Ok ,Thx..I will handle it as soon as I can.

**Comment by luckysmg** [comment]
I have pushed v1.0.9.You can try it ^_^... @play0sm

**Comment by play0sm** [comment]
Yes it's work. Thx :)
