### ISSUE TITLE
如何设置滑动后的回弹效果

### ISSUE THREAD

**Issue by kennir** [luckysmg/flutter_swipe_action_cell#63]
感谢插件作者，我想实现如视频里这样的回弹效果，是否可以自定义动画？ 

https://github.com/luckysmg/flutter_swipe_action_cell/assets/876410/f24bdbde-c7f5-4f97-84c5-7d8b90ce2b9d

看了一下代码， 我觉得首先需要修改普通的动画的曲线为 easeOutBack
```
    curvedAnim = CurvedAnimation(parent: controller, curve: Curves.easeOutBack);
```

其次，我认为需要再增加一个 animation 作为收回的动画（不需要 easeOutBack）

不知道这个思路是否正确？ 

谢谢

**Comment by luckysmg** [comment]
我理解是不是只动Curve就行了

**Comment by kennir** [comment]
> 我理解是不是只动Curve就行了

感谢回复

我尝试了修改只修改了 curve，似乎收回使用的也是这个 controller，所以收回cell的时候也会有 easeOutBack 的效果， 而我想收回的时候使用 easeOut 就可以了

**Comment by luckysmg** [comment]
那无非是关闭和开启用不同的Curve

**Comment by luckysmg** [comment]
现在curve在关闭和开启都用的一个，可以弄成分开来的，开启的时候用一个，关闭的时候用另外一个即可

**Comment by kennir** [comment]
感谢答复，感谢作者提供了这么好的插件

**Comment by luckysmg** [comment]
这个回头我做上去吧，不过最近没啥时间，急的话你先fork一份自己改改，issue先开着

**Comment by luckysmg** [comment]
3.1.2已经发布上pub，可以稍后使用
