### ISSUE TITLE
Assertion error during edit mode on second list

### ISSUE THREAD

**Issue by SoMWbRa** [luckysmg/flutter_swipe_action_cell#71]
**Description**

An error occurs when trying to perform actions in edit mode on a second list. The issue arises when the SwipeActionCell is used on two different lists, where one of the lists doesn't use a controller or index, but the other one does. When entering the edit mode on the second list (which has the controller and index), the following assertion error appears in the console:

`
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter_swipe_action_cell/core/cell.dart': Failed assertion: line 306 pos 14: 'widget.controller != null && widget.index != null': is not true.
E/flutter (26883): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:50:61)
E/flutter (26883): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (26883): #2      SwipeActionCellState._listenEvent.<anonymous closure> (package:flutter_swipe_action_cell/core/cell.dart:306:14)
E/flutter (26883): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (26883): #4      CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
E/flutter (26883): #5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (26883): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
E/flutter (26883): #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
E/flutter (26883): #8      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (26883): #9      _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
E/flutter (26883): #10     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (26883): #11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (26883): #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
E/flutter (26883): #13     _DelayedData.perform (dart:async/stream_impl.dart:541:14)
E/flutter (26883): #14     _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
E/flutter (26883): #15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
E/flutter (26883): #16     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (26883): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (26883): 
`

**Steps to Reproduce**
1. Create two separate lists using the SwipeActionCell widget. The lists can be on different screens, between which you navigate via `Navigator.of(context).push`.
2. For the first list, do not provide a controller or index.
3. For the second list, provide a SwipeActionController and set the index.
4. Enter the edit mode on the second list and perform `controller.selectCellAt`
6. Observe the error in the console.

**Code sample**
```
import 'package:flutter/material.dart';
import 'package:flutter_swipe_action_cell/flutter_swipe_action_cell.dart';

class BugReproduce extends StatefulWidget {
  const BugReproduce({super.key});

  @override
  State<BugReproduce> createState() => _BugReproduceState();
}

class _BugReproduceState extends State<BugReproduce> {
  final SwipeActionController _swipeActionController = SwipeActionController();
  final SwipeActionController _anotherActionController = SwipeActionController();

  final List<String> words = <String>[
    'Apple',
    'Banana',
    'Cherry',
    'Date',
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: ListView.builder(
              itemCount: 5,
              itemBuilder: (context, index) {
                final number = index + 1;
                return SwipeActionCell(
                  key: ObjectKey(number),
                  // Uncomment this lines to fix the issue
                  // index: index,
                  // controller: _anotherActionController,
                  trailingActions: [
                    SwipeAction(
                      onTap: (handler) async {
                        await handler(false);
                      },
                      color: Colors.grey,
                      icon: const Icon(Icons.edit, color: Colors.white),
                    )
                  ],
                  child: ListTile(
                    title: Text("Number $number"),
                  ),
                );
              },
            ),
          ),
          Expanded(
            child: ListView.builder(
              itemCount: words.length,
              itemBuilder: (context, index) {
                final word = words[index];
                return SwipeActionCell(
                  key: ObjectKey(word),
                  index: index,
                  controller: _swipeActionController,
                  child: ListTile(
                    title: Text(word),
                    onLongPress: () {
                      _swipeActionController.startEditingMode();
                      _swipeActionController.selectCellAt(indexPaths: [index]);
                    },
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}

```
**Workaround**
Uncommenting the index and controller lines in the first list resolves the issue. However, the library should handle the case when these properties are not provided to prevent this assertion error.

**Expected Behavior**
SwipeActionCell should not conflict with each other.

**Comment by luckysmg** [comment]
Plz use new version on pub `3.1.5`
