### ISSUE TITLE
Number of elements selected in edit mode

### ISSUE THREAD

**Issue by dariolr** [luckysmg/flutter_swipe_action_cell#9]
Hello, thanks for your helpful work

is there a way to get the number of elements selected in edit mode?

**Comment by luckysmg** [comment]
maybe you can call getSeletedIndexPaths to get a List,and you can call list.length to get the num...

**Comment by luckysmg** [comment]
maybe I know what you need. Do you want to know the current selected count every time you select or deselect an element?

**Comment by dariolr** [comment]
yes, that's exactly what I need :)

**Comment by luckysmg** [comment]
Ok ，may be I forgot this function...I will develop this func as soon as I can.Plz focus on the next version.Thx

**Comment by dariolr** [comment]
Thanks a lot

**Comment by luckysmg** [comment]
I have push version v1.2.2.You can try it...If there are any bugs,please contact me ^_^

**Comment by luckysmg** [comment]
You can find demo code in pub example page

**Comment by dariolr** [comment]
Thank you! I will test tomorrow

**Comment by dariolr** [comment]
it works perfectly

thank you!!!!

**Comment by dariolr** [comment]
...maybe you want to close it yourself

**Comment by luckysmg** [comment]
ok I ll handle it



发自我的iPhone


------------------ Original ------------------
